[package]
name = "safe-ffi"
version = "0.8.0"
description = "SAFE API FFI"
authors = ["Ravinder Jangra <ravinderjangra@live.com>"]
publish = false
license = "MIT OR BSD-3-Clause"
repository = "https://github.com/maidsafe/safe-api"
build = "build.rs"
edition = "2018"

[lib]
name = "safe_ffi"
crate_type = ["staticlib", "rlib", "cdylib"]
path = "lib.rs"

[dependencies]
ffi_utils = "~0.14.0"
# Required by ffi_utils macros.
log = "~0.4.8"
safe-api = { path = "../safe-api" }
#safe-nd = "~0.7.2"
safe-nd = { git = 'https://github.com/oetyng/safe-nd/', branch = "replace-ad-with-sequence" }
serde = "1.0.91"
serde_json = "1.0.39"

[dev-dependencies]
unwrap = "~1.2.1"

[build-dependencies]
safe_bindgen = { version = "~0.13.2", optional = true }
#safe-nd = "~0.7.2"
safe-nd = { git = 'https://github.com/oetyng/safe-nd/', branch = "replace-ad-with-sequence" }
unwrap = "~1.2.1"

[features]
mock-network = ["safe-api/mock-network"]
fake-auth = ["safe-api/fake-auth"]
bindings = ["safe_bindgen"]
